apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: ["--dockerfile=./Dockerfile",
               "--context=git://github.com/srizwan101/kaniko.git#refs/heads/main",
               "--destination=localhost:5000/ownnginx:v1"]
        volumeMounts:
        - name: kaniko-secret3
          mountPath: "/kaniko/.docker"
      restartPolicy: Never
      volumes:
      - name: kaniko-secret3
        
